name: rwa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^2.0.1
  http: ^0.13.0
  progress_dialog: ^1.2.4
  cached_network_image: ^2.1.0+1
  fluttertoast: ^8.0.8
  page_transition: ^2.0.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  google_fonts: ^2.1.0
  image_picker: ^0.6.4
  mime: ^0.9.6+3
  intl: ^0.17.0
  toggle_switch: ^1.3.0
  url_launcher: ^6.0.5
  razorpay_flutter: ^1.2.6
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^8.2.0
  wakelock: ^0.5.6
  jiffy: ^5.0.0
  syncfusion_flutter_charts: ^19.2.49
  syncfusion_flutter_pdfviewer: ^19.2.51-beta
  new_version: ^0.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/login_rectangle.png
    - assets/images/rwa_logo.png
    - assets/images/nav_icon.png
    - assets/images/profile.png
    - assets/images/phone.png
    - assets/images/chat.png
    - assets/images/home.png
    - assets/images/weather.png
    - assets/images/dashboard.png
    - assets/images/complaint.png
    - assets/images/member_search.png
    - assets/images/dues.png
    - assets/images/userimg.png
    - assets/images/log_out.png
    - assets/images/complaints_graph.png
    - assets/images/forums.png
    - assets/images/environment.png
    - assets/images/attached.png
    - assets/images/user.png
    - assets/images/calendar.png
    - assets/images/category.png
    - assets/images/date.png
    - assets/images/rupee.png
    - assets/images/member.png
    - assets/images/email.png
    - assets/images/address.png
    - assets/images/house_no.png
    - assets/images/notice_board.png
    - assets/images/docs.png
    - assets/images/emergency.png
    - assets/images/sos_image.png
    - assets/images/receipt_list.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
